### ISSUE TITLE
Why I have to use the index number 0 after parsing an array?

### ISSUE THREAD

**Issue by j0nnib0y** [Kandru/TS3eventscripts#1]
Ehhm, I know why because I've seen the code, but I think it isn't right.
The following example does explain my question:

```php
// array comes from loop
$pretty = EVmain::parse($array["msg"]);
if(isset($pretty[0]["ev_type"]) and ($pretty[0]["ev_type"] == "notifycliententerview")) {
	EVts3::sendmessage(1, $pretty[0]["clid"], "Bla!");
}
```
In your example it doesn't need an index.

**Comment by Kandru** [comment]
Hey @j0nnib0y, 

should be fixed now! Have a look at the current trunk.
